"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['idslabel.py']
DATA_FILES = ['include/idslabel.icns', 'include/ffmpeg']
OPTIONS = {'argv_emulation': True,
           'plist': {
               'CFBundleIconFile': 'idslabel.icns'
                }
           }
VERSION="0.0.2"

setup(
    app=APP,
    name='IDSLabel',
    data_files=DATA_FILES,
    version=VERSION,
    iconfile="idslabel.icns",
    resources='include',
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
